// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/protobuf/compiler/plugin.proto

#ifndef PROTOBUF_INCLUDED_googlex2fprotobuf_2fcompiler_2fplugin_2eproto
#define PROTOBUF_INCLUDED_googlex2fprotobuf_2fcompiler_2fplugin_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include <google/protobuf/descriptor.pb.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_googlex2fprotobuf_2fcompiler_2fplugin_2eproto LIBPROTOC_EXPORT
#ifdef major
#undef major
#endif
#ifdef minor
#undef minor
#endif

namespace protobuf_googlex2fprotobuf_2fcompiler_2fplugin_2eproto {
// Internal implementation detail -- do not use these members.
struct LIBPROTOC_EXPORT TableStruct {
  static const ::googlex::protobuf::internal::ParseTableField entries[];
  static const ::googlex::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::googlex::protobuf::internal::ParseTable schema[4];
  static const ::googlex::protobuf::internal::FieldMetadata field_metadata[];
  static const ::googlex::protobuf::internal::SerializationTable serialization_table[];
  static const ::googlex::protobuf::uint32 offsets[];
};
void LIBPROTOC_EXPORT AddDescriptors();
}  // namespace protobuf_googlex2fprotobuf_2fcompiler_2fplugin_2eproto
namespace googlex{
namespace protobuf {
namespace compiler {
class CodeGeneratorRequest;
class CodeGeneratorRequestDefaultTypeInternal;
LIBPROTOC_EXPORT extern CodeGeneratorRequestDefaultTypeInternal _CodeGeneratorRequest_default_instance_;
class CodeGeneratorResponse;
class CodeGeneratorResponseDefaultTypeInternal;
LIBPROTOC_EXPORT extern CodeGeneratorResponseDefaultTypeInternal _CodeGeneratorResponse_default_instance_;
class CodeGeneratorResponse_File;
class CodeGeneratorResponse_FileDefaultTypeInternal;
LIBPROTOC_EXPORT extern CodeGeneratorResponse_FileDefaultTypeInternal _CodeGeneratorResponse_File_default_instance_;
class Version;
class VersionDefaultTypeInternal;
LIBPROTOC_EXPORT extern VersionDefaultTypeInternal _Version_default_instance_;
}  // namespace compiler
}  // namespace protobuf
}  // namespace google
namespace googlex{
namespace protobuf {
template<> LIBPROTOC_EXPORT ::googlex::protobuf::compiler::CodeGeneratorRequest* Arena::CreateMaybeMessage<::googlex::protobuf::compiler::CodeGeneratorRequest>(Arena*);
template<> LIBPROTOC_EXPORT ::googlex::protobuf::compiler::CodeGeneratorResponse* Arena::CreateMaybeMessage<::googlex::protobuf::compiler::CodeGeneratorResponse>(Arena*);
template<> LIBPROTOC_EXPORT ::googlex::protobuf::compiler::CodeGeneratorResponse_File* Arena::CreateMaybeMessage<::googlex::protobuf::compiler::CodeGeneratorResponse_File>(Arena*);
template<> LIBPROTOC_EXPORT ::googlex::protobuf::compiler::Version* Arena::CreateMaybeMessage<::googlex::protobuf::compiler::Version>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace googlex{
namespace protobuf {
namespace compiler {

// ===================================================================

class LIBPROTOC_EXPORT Version : public ::googlex::protobuf::Message /* @@protoc_insertion_point(class_definition:googlexprotobuf.compiler.Version) */ {
 public:
  Version();
  virtual ~Version();

  Version(const Version& from);

  inline Version& operator=(const Version& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Version(Version&& from) noexcept
    : Version() {
    *this = ::std::move(from);
  }

  inline Version& operator=(Version&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::googlex::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::googlex::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::googlex::protobuf::Descriptor* descriptor();
  static const Version& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Version* internal_default_instance() {
    return reinterpret_cast<const Version*>(
               &_Version_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(Version* other);
  friend void swap(Version& a, Version& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Version* New() const final {
    return CreateMaybeMessage<Version>(NULL);
  }

  Version* New(::googlex::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Version>(arena);
  }
  void CopyFrom(const ::googlex::protobuf::Message& from) final;
  void MergeFrom(const ::googlex::protobuf::Message& from) final;
  void CopyFrom(const Version& from);
  void MergeFrom(const Version& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::googlex::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::googlex::protobuf::io::CodedOutputStream* output) const final;
  ::googlex::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::googlex::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Version* other);
  private:
  inline ::googlex::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::googlex::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string suffix = 4;
  bool has_suffix() const;
  void clear_suffix();
  static const int kSuffixFieldNumber = 4;
  const ::std::string& suffix() const;
  void set_suffix(const ::std::string& value);
  #if LANG_CXX11
  void set_suffix(::std::string&& value);
  #endif
  void set_suffix(const char* value);
  void set_suffix(const char* value, size_t size);
  ::std::string* mutable_suffix();
  ::std::string* release_suffix();
  void set_allocated_suffix(::std::string* suffix);

  // optional int32 major = 1;
  bool has_major() const;
  void clear_major();
  static const int kMajorFieldNumber = 1;
  ::googlex::protobuf::int32 major() const;
  void set_major(::googlex::protobuf::int32 value);

  // optional int32 minor = 2;
  bool has_minor() const;
  void clear_minor();
  static const int kMinorFieldNumber = 2;
  ::googlex::protobuf::int32 minor() const;
  void set_minor(::googlex::protobuf::int32 value);

  // optional int32 patch = 3;
  bool has_patch() const;
  void clear_patch();
  static const int kPatchFieldNumber = 3;
  ::googlex::protobuf::int32 patch() const;
  void set_patch(::googlex::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:googlexprotobuf.compiler.Version)
 private:
  void set_has_major();
  void clear_has_major();
  void set_has_minor();
  void clear_has_minor();
  void set_has_patch();
  void clear_has_patch();
  void set_has_suffix();
  void clear_has_suffix();

  ::googlex::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::googlex::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::googlex::protobuf::internal::CachedSize _cached_size_;
  ::googlex::protobuf::internal::ArenaStringPtr suffix_;
  ::googlex::protobuf::int32 major_;
  ::googlex::protobuf::int32 minor_;
  ::googlex::protobuf::int32 patch_;
  friend struct ::protobuf_googlex2fprotobuf_2fcompiler_2fplugin_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class LIBPROTOC_EXPORT CodeGeneratorRequest : public ::googlex::protobuf::Message /* @@protoc_insertion_point(class_definition:googlexprotobuf.compiler.CodeGeneratorRequest) */ {
 public:
  CodeGeneratorRequest();
  virtual ~CodeGeneratorRequest();

  CodeGeneratorRequest(const CodeGeneratorRequest& from);

  inline CodeGeneratorRequest& operator=(const CodeGeneratorRequest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  CodeGeneratorRequest(CodeGeneratorRequest&& from) noexcept
    : CodeGeneratorRequest() {
    *this = ::std::move(from);
  }

  inline CodeGeneratorRequest& operator=(CodeGeneratorRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::googlex::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::googlex::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::googlex::protobuf::Descriptor* descriptor();
  static const CodeGeneratorRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const CodeGeneratorRequest* internal_default_instance() {
    return reinterpret_cast<const CodeGeneratorRequest*>(
               &_CodeGeneratorRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(CodeGeneratorRequest* other);
  friend void swap(CodeGeneratorRequest& a, CodeGeneratorRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline CodeGeneratorRequest* New() const final {
    return CreateMaybeMessage<CodeGeneratorRequest>(NULL);
  }

  CodeGeneratorRequest* New(::googlex::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<CodeGeneratorRequest>(arena);
  }
  void CopyFrom(const ::googlex::protobuf::Message& from) final;
  void MergeFrom(const ::googlex::protobuf::Message& from) final;
  void CopyFrom(const CodeGeneratorRequest& from);
  void MergeFrom(const CodeGeneratorRequest& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::googlex::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::googlex::protobuf::io::CodedOutputStream* output) const final;
  ::googlex::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::googlex::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CodeGeneratorRequest* other);
  private:
  inline ::googlex::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::googlex::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated string file_to_generate = 1;
  int file_to_generate_size() const;
  void clear_file_to_generate();
  static const int kFileToGenerateFieldNumber = 1;
  const ::std::string& file_to_generate(int index) const;
  ::std::string* mutable_file_to_generate(int index);
  void set_file_to_generate(int index, const ::std::string& value);
  #if LANG_CXX11
  void set_file_to_generate(int index, ::std::string&& value);
  #endif
  void set_file_to_generate(int index, const char* value);
  void set_file_to_generate(int index, const char* value, size_t size);
  ::std::string* add_file_to_generate();
  void add_file_to_generate(const ::std::string& value);
  #if LANG_CXX11
  void add_file_to_generate(::std::string&& value);
  #endif
  void add_file_to_generate(const char* value);
  void add_file_to_generate(const char* value, size_t size);
  const ::googlex::protobuf::RepeatedPtrField< ::std::string>& file_to_generate() const;
  ::googlex::protobuf::RepeatedPtrField< ::std::string>* mutable_file_to_generate();

  // repeated .googlexprotobuf.FileDescriptorProto proto_file = 15;
  int proto_file_size() const;
  void clear_proto_file();
  static const int kProtoFileFieldNumber = 15;
  ::googlex::protobuf::FileDescriptorProto* mutable_proto_file(int index);
  ::googlex::protobuf::RepeatedPtrField< ::googlex::protobuf::FileDescriptorProto >*
      mutable_proto_file();
  const ::googlex::protobuf::FileDescriptorProto& proto_file(int index) const;
  ::googlex::protobuf::FileDescriptorProto* add_proto_file();
  const ::googlex::protobuf::RepeatedPtrField< ::googlex::protobuf::FileDescriptorProto >&
      proto_file() const;

  // optional string parameter = 2;
  bool has_parameter() const;
  void clear_parameter();
  static const int kParameterFieldNumber = 2;
  const ::std::string& parameter() const;
  void set_parameter(const ::std::string& value);
  #if LANG_CXX11
  void set_parameter(::std::string&& value);
  #endif
  void set_parameter(const char* value);
  void set_parameter(const char* value, size_t size);
  ::std::string* mutable_parameter();
  ::std::string* release_parameter();
  void set_allocated_parameter(::std::string* parameter);

  // optional .googlexprotobuf.compiler.Version compiler_version = 3;
  bool has_compiler_version() const;
  void clear_compiler_version();
  static const int kCompilerVersionFieldNumber = 3;
  private:
  const ::googlex::protobuf::compiler::Version& _internal_compiler_version() const;
  public:
  const ::googlex::protobuf::compiler::Version& compiler_version() const;
  ::googlex::protobuf::compiler::Version* release_compiler_version();
  ::googlex::protobuf::compiler::Version* mutable_compiler_version();
  void set_allocated_compiler_version(::googlex::protobuf::compiler::Version* compiler_version);

  // @@protoc_insertion_point(class_scope:googlexprotobuf.compiler.CodeGeneratorRequest)
 private:
  void set_has_parameter();
  void clear_has_parameter();
  void set_has_compiler_version();
  void clear_has_compiler_version();

  ::googlex::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::googlex::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::googlex::protobuf::internal::CachedSize _cached_size_;
  ::googlex::protobuf::RepeatedPtrField< ::std::string> file_to_generate_;
  ::googlex::protobuf::RepeatedPtrField< ::googlex::protobuf::FileDescriptorProto > proto_file_;
  ::googlex::protobuf::internal::ArenaStringPtr parameter_;
  ::googlex::protobuf::compiler::Version* compiler_version_;
  friend struct ::protobuf_googlex2fprotobuf_2fcompiler_2fplugin_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class LIBPROTOC_EXPORT CodeGeneratorResponse_File : public ::googlex::protobuf::Message /* @@protoc_insertion_point(class_definition:googlexprotobuf.compiler.CodeGeneratorResponse.File) */ {
 public:
  CodeGeneratorResponse_File();
  virtual ~CodeGeneratorResponse_File();

  CodeGeneratorResponse_File(const CodeGeneratorResponse_File& from);

  inline CodeGeneratorResponse_File& operator=(const CodeGeneratorResponse_File& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  CodeGeneratorResponse_File(CodeGeneratorResponse_File&& from) noexcept
    : CodeGeneratorResponse_File() {
    *this = ::std::move(from);
  }

  inline CodeGeneratorResponse_File& operator=(CodeGeneratorResponse_File&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::googlex::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::googlex::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::googlex::protobuf::Descriptor* descriptor();
  static const CodeGeneratorResponse_File& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const CodeGeneratorResponse_File* internal_default_instance() {
    return reinterpret_cast<const CodeGeneratorResponse_File*>(
               &_CodeGeneratorResponse_File_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(CodeGeneratorResponse_File* other);
  friend void swap(CodeGeneratorResponse_File& a, CodeGeneratorResponse_File& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline CodeGeneratorResponse_File* New() const final {
    return CreateMaybeMessage<CodeGeneratorResponse_File>(NULL);
  }

  CodeGeneratorResponse_File* New(::googlex::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<CodeGeneratorResponse_File>(arena);
  }
  void CopyFrom(const ::googlex::protobuf::Message& from) final;
  void MergeFrom(const ::googlex::protobuf::Message& from) final;
  void CopyFrom(const CodeGeneratorResponse_File& from);
  void MergeFrom(const CodeGeneratorResponse_File& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::googlex::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::googlex::protobuf::io::CodedOutputStream* output) const final;
  ::googlex::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::googlex::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CodeGeneratorResponse_File* other);
  private:
  inline ::googlex::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::googlex::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string name = 1;
  bool has_name() const;
  void clear_name();
  static const int kNameFieldNumber = 1;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  #if LANG_CXX11
  void set_name(::std::string&& value);
  #endif
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // optional string insertion_point = 2;
  bool has_insertion_point() const;
  void clear_insertion_point();
  static const int kInsertionPointFieldNumber = 2;
  const ::std::string& insertion_point() const;
  void set_insertion_point(const ::std::string& value);
  #if LANG_CXX11
  void set_insertion_point(::std::string&& value);
  #endif
  void set_insertion_point(const char* value);
  void set_insertion_point(const char* value, size_t size);
  ::std::string* mutable_insertion_point();
  ::std::string* release_insertion_point();
  void set_allocated_insertion_point(::std::string* insertion_point);

  // optional string content = 15;
  bool has_content() const;
  void clear_content();
  static const int kContentFieldNumber = 15;
  const ::std::string& content() const;
  void set_content(const ::std::string& value);
  #if LANG_CXX11
  void set_content(::std::string&& value);
  #endif
  void set_content(const char* value);
  void set_content(const char* value, size_t size);
  ::std::string* mutable_content();
  ::std::string* release_content();
  void set_allocated_content(::std::string* content);

  // @@protoc_insertion_point(class_scope:googlexprotobuf.compiler.CodeGeneratorResponse.File)
 private:
  void set_has_name();
  void clear_has_name();
  void set_has_insertion_point();
  void clear_has_insertion_point();
  void set_has_content();
  void clear_has_content();

  ::googlex::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::googlex::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::googlex::protobuf::internal::CachedSize _cached_size_;
  ::googlex::protobuf::internal::ArenaStringPtr name_;
  ::googlex::protobuf::internal::ArenaStringPtr insertion_point_;
  ::googlex::protobuf::internal::ArenaStringPtr content_;
  friend struct ::protobuf_googlex2fprotobuf_2fcompiler_2fplugin_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class LIBPROTOC_EXPORT CodeGeneratorResponse : public ::googlex::protobuf::Message /* @@protoc_insertion_point(class_definition:googlexprotobuf.compiler.CodeGeneratorResponse) */ {
 public:
  CodeGeneratorResponse();
  virtual ~CodeGeneratorResponse();

  CodeGeneratorResponse(const CodeGeneratorResponse& from);

  inline CodeGeneratorResponse& operator=(const CodeGeneratorResponse& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  CodeGeneratorResponse(CodeGeneratorResponse&& from) noexcept
    : CodeGeneratorResponse() {
    *this = ::std::move(from);
  }

  inline CodeGeneratorResponse& operator=(CodeGeneratorResponse&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::googlex::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::googlex::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::googlex::protobuf::Descriptor* descriptor();
  static const CodeGeneratorResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const CodeGeneratorResponse* internal_default_instance() {
    return reinterpret_cast<const CodeGeneratorResponse*>(
               &_CodeGeneratorResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  void Swap(CodeGeneratorResponse* other);
  friend void swap(CodeGeneratorResponse& a, CodeGeneratorResponse& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline CodeGeneratorResponse* New() const final {
    return CreateMaybeMessage<CodeGeneratorResponse>(NULL);
  }

  CodeGeneratorResponse* New(::googlex::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<CodeGeneratorResponse>(arena);
  }
  void CopyFrom(const ::googlex::protobuf::Message& from) final;
  void MergeFrom(const ::googlex::protobuf::Message& from) final;
  void CopyFrom(const CodeGeneratorResponse& from);
  void MergeFrom(const CodeGeneratorResponse& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::googlex::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::googlex::protobuf::io::CodedOutputStream* output) const final;
  ::googlex::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::googlex::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CodeGeneratorResponse* other);
  private:
  inline ::googlex::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::googlex::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef CodeGeneratorResponse_File File;

  // accessors -------------------------------------------------------

  // repeated .googlexprotobuf.compiler.CodeGeneratorResponse.File file = 15;
  int file_size() const;
  void clear_file();
  static const int kFileFieldNumber = 15;
  ::googlex::protobuf::compiler::CodeGeneratorResponse_File* mutable_file(int index);
  ::googlex::protobuf::RepeatedPtrField< ::googlex::protobuf::compiler::CodeGeneratorResponse_File >*
      mutable_file();
  const ::googlex::protobuf::compiler::CodeGeneratorResponse_File& file(int index) const;
  ::googlex::protobuf::compiler::CodeGeneratorResponse_File* add_file();
  const ::googlex::protobuf::RepeatedPtrField< ::googlex::protobuf::compiler::CodeGeneratorResponse_File >&
      file() const;

  // optional string error = 1;
  bool has_error() const;
  void clear_error();
  static const int kErrorFieldNumber = 1;
  const ::std::string& error() const;
  void set_error(const ::std::string& value);
  #if LANG_CXX11
  void set_error(::std::string&& value);
  #endif
  void set_error(const char* value);
  void set_error(const char* value, size_t size);
  ::std::string* mutable_error();
  ::std::string* release_error();
  void set_allocated_error(::std::string* error);

  // @@protoc_insertion_point(class_scope:googlexprotobuf.compiler.CodeGeneratorResponse)
 private:
  void set_has_error();
  void clear_has_error();

  ::googlex::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::googlex::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::googlex::protobuf::internal::CachedSize _cached_size_;
  ::googlex::protobuf::RepeatedPtrField< ::googlex::protobuf::compiler::CodeGeneratorResponse_File > file_;
  ::googlex::protobuf::internal::ArenaStringPtr error_;
  friend struct ::protobuf_googlex2fprotobuf_2fcompiler_2fplugin_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Version

// optional int32 major = 1;
inline bool Version::has_major() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Version::set_has_major() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Version::clear_has_major() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Version::clear_major() {
  major_ = 0;
  clear_has_major();
}
inline ::googlex::protobuf::int32 Version::major() const {
  // @@protoc_insertion_point(field_get:googlexprotobuf.compiler.Version.major)
  return major_;
}
inline void Version::set_major(::googlex::protobuf::int32 value) {
  set_has_major();
  major_ = value;
  // @@protoc_insertion_point(field_set:googlexprotobuf.compiler.Version.major)
}

// optional int32 minor = 2;
inline bool Version::has_minor() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Version::set_has_minor() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Version::clear_has_minor() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Version::clear_minor() {
  minor_ = 0;
  clear_has_minor();
}
inline ::googlex::protobuf::int32 Version::minor() const {
  // @@protoc_insertion_point(field_get:googlexprotobuf.compiler.Version.minor)
  return minor_;
}
inline void Version::set_minor(::googlex::protobuf::int32 value) {
  set_has_minor();
  minor_ = value;
  // @@protoc_insertion_point(field_set:googlexprotobuf.compiler.Version.minor)
}

// optional int32 patch = 3;
inline bool Version::has_patch() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Version::set_has_patch() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Version::clear_has_patch() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Version::clear_patch() {
  patch_ = 0;
  clear_has_patch();
}
inline ::googlex::protobuf::int32 Version::patch() const {
  // @@protoc_insertion_point(field_get:googlexprotobuf.compiler.Version.patch)
  return patch_;
}
inline void Version::set_patch(::googlex::protobuf::int32 value) {
  set_has_patch();
  patch_ = value;
  // @@protoc_insertion_point(field_set:googlexprotobuf.compiler.Version.patch)
}

// optional string suffix = 4;
inline bool Version::has_suffix() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Version::set_has_suffix() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Version::clear_has_suffix() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Version::clear_suffix() {
  suffix_.ClearToEmptyNoArena(&::googlex::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_suffix();
}
inline const ::std::string& Version::suffix() const {
  // @@protoc_insertion_point(field_get:googlexprotobuf.compiler.Version.suffix)
  return suffix_.GetNoArena();
}
inline void Version::set_suffix(const ::std::string& value) {
  set_has_suffix();
  suffix_.SetNoArena(&::googlex::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:googlexprotobuf.compiler.Version.suffix)
}
#if LANG_CXX11
inline void Version::set_suffix(::std::string&& value) {
  set_has_suffix();
  suffix_.SetNoArena(
    &::googlex::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:googlexprotobuf.compiler.Version.suffix)
}
#endif
inline void Version::set_suffix(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_suffix();
  suffix_.SetNoArena(&::googlex::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:googlexprotobuf.compiler.Version.suffix)
}
inline void Version::set_suffix(const char* value, size_t size) {
  set_has_suffix();
  suffix_.SetNoArena(&::googlex::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:googlexprotobuf.compiler.Version.suffix)
}
inline ::std::string* Version::mutable_suffix() {
  set_has_suffix();
  // @@protoc_insertion_point(field_mutable:googlexprotobuf.compiler.Version.suffix)
  return suffix_.MutableNoArena(&::googlex::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Version::release_suffix() {
  // @@protoc_insertion_point(field_release:googlexprotobuf.compiler.Version.suffix)
  if (!has_suffix()) {
    return NULL;
  }
  clear_has_suffix();
  return suffix_.ReleaseNonDefaultNoArena(&::googlex::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Version::set_allocated_suffix(::std::string* suffix) {
  if (suffix != NULL) {
    set_has_suffix();
  } else {
    clear_has_suffix();
  }
  suffix_.SetAllocatedNoArena(&::googlex::protobuf::internal::GetEmptyStringAlreadyInited(), suffix);
  // @@protoc_insertion_point(field_set_allocated:googlexprotobuf.compiler.Version.suffix)
}

// -------------------------------------------------------------------

// CodeGeneratorRequest

// repeated string file_to_generate = 1;
inline int CodeGeneratorRequest::file_to_generate_size() const {
  return file_to_generate_.size();
}
inline void CodeGeneratorRequest::clear_file_to_generate() {
  file_to_generate_.Clear();
}
inline const ::std::string& CodeGeneratorRequest::file_to_generate(int index) const {
  // @@protoc_insertion_point(field_get:googlexprotobuf.compiler.CodeGeneratorRequest.file_to_generate)
  return file_to_generate_.Get(index);
}
inline ::std::string* CodeGeneratorRequest::mutable_file_to_generate(int index) {
  // @@protoc_insertion_point(field_mutable:googlexprotobuf.compiler.CodeGeneratorRequest.file_to_generate)
  return file_to_generate_.Mutable(index);
}
inline void CodeGeneratorRequest::set_file_to_generate(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:googlexprotobuf.compiler.CodeGeneratorRequest.file_to_generate)
  file_to_generate_.Mutable(index)->assign(value);
}
#if LANG_CXX11
inline void CodeGeneratorRequest::set_file_to_generate(int index, ::std::string&& value) {
  // @@protoc_insertion_point(field_set:googlexprotobuf.compiler.CodeGeneratorRequest.file_to_generate)
  file_to_generate_.Mutable(index)->assign(std::move(value));
}
#endif
inline void CodeGeneratorRequest::set_file_to_generate(int index, const char* value) {
  GOOGLE_DCHECK(value != NULL);
  file_to_generate_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:googlexprotobuf.compiler.CodeGeneratorRequest.file_to_generate)
}
inline void CodeGeneratorRequest::set_file_to_generate(int index, const char* value, size_t size) {
  file_to_generate_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:googlexprotobuf.compiler.CodeGeneratorRequest.file_to_generate)
}
inline ::std::string* CodeGeneratorRequest::add_file_to_generate() {
  // @@protoc_insertion_point(field_add_mutable:googlexprotobuf.compiler.CodeGeneratorRequest.file_to_generate)
  return file_to_generate_.Add();
}
inline void CodeGeneratorRequest::add_file_to_generate(const ::std::string& value) {
  file_to_generate_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:googlexprotobuf.compiler.CodeGeneratorRequest.file_to_generate)
}
#if LANG_CXX11
inline void CodeGeneratorRequest::add_file_to_generate(::std::string&& value) {
  file_to_generate_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:googlexprotobuf.compiler.CodeGeneratorRequest.file_to_generate)
}
#endif
inline void CodeGeneratorRequest::add_file_to_generate(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  file_to_generate_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:googlexprotobuf.compiler.CodeGeneratorRequest.file_to_generate)
}
inline void CodeGeneratorRequest::add_file_to_generate(const char* value, size_t size) {
  file_to_generate_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:googlexprotobuf.compiler.CodeGeneratorRequest.file_to_generate)
}
inline const ::googlex::protobuf::RepeatedPtrField< ::std::string>&
CodeGeneratorRequest::file_to_generate() const {
  // @@protoc_insertion_point(field_list:googlexprotobuf.compiler.CodeGeneratorRequest.file_to_generate)
  return file_to_generate_;
}
inline ::googlex::protobuf::RepeatedPtrField< ::std::string>*
CodeGeneratorRequest::mutable_file_to_generate() {
  // @@protoc_insertion_point(field_mutable_list:googlexprotobuf.compiler.CodeGeneratorRequest.file_to_generate)
  return &file_to_generate_;
}

// optional string parameter = 2;
inline bool CodeGeneratorRequest::has_parameter() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CodeGeneratorRequest::set_has_parameter() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CodeGeneratorRequest::clear_has_parameter() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CodeGeneratorRequest::clear_parameter() {
  parameter_.ClearToEmptyNoArena(&::googlex::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_parameter();
}
inline const ::std::string& CodeGeneratorRequest::parameter() const {
  // @@protoc_insertion_point(field_get:googlexprotobuf.compiler.CodeGeneratorRequest.parameter)
  return parameter_.GetNoArena();
}
inline void CodeGeneratorRequest::set_parameter(const ::std::string& value) {
  set_has_parameter();
  parameter_.SetNoArena(&::googlex::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:googlexprotobuf.compiler.CodeGeneratorRequest.parameter)
}
#if LANG_CXX11
inline void CodeGeneratorRequest::set_parameter(::std::string&& value) {
  set_has_parameter();
  parameter_.SetNoArena(
    &::googlex::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:googlexprotobuf.compiler.CodeGeneratorRequest.parameter)
}
#endif
inline void CodeGeneratorRequest::set_parameter(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_parameter();
  parameter_.SetNoArena(&::googlex::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:googlexprotobuf.compiler.CodeGeneratorRequest.parameter)
}
inline void CodeGeneratorRequest::set_parameter(const char* value, size_t size) {
  set_has_parameter();
  parameter_.SetNoArena(&::googlex::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:googlexprotobuf.compiler.CodeGeneratorRequest.parameter)
}
inline ::std::string* CodeGeneratorRequest::mutable_parameter() {
  set_has_parameter();
  // @@protoc_insertion_point(field_mutable:googlexprotobuf.compiler.CodeGeneratorRequest.parameter)
  return parameter_.MutableNoArena(&::googlex::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CodeGeneratorRequest::release_parameter() {
  // @@protoc_insertion_point(field_release:googlexprotobuf.compiler.CodeGeneratorRequest.parameter)
  if (!has_parameter()) {
    return NULL;
  }
  clear_has_parameter();
  return parameter_.ReleaseNonDefaultNoArena(&::googlex::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CodeGeneratorRequest::set_allocated_parameter(::std::string* parameter) {
  if (parameter != NULL) {
    set_has_parameter();
  } else {
    clear_has_parameter();
  }
  parameter_.SetAllocatedNoArena(&::googlex::protobuf::internal::GetEmptyStringAlreadyInited(), parameter);
  // @@protoc_insertion_point(field_set_allocated:googlexprotobuf.compiler.CodeGeneratorRequest.parameter)
}

// repeated .googlexprotobuf.FileDescriptorProto proto_file = 15;
inline int CodeGeneratorRequest::proto_file_size() const {
  return proto_file_.size();
}
inline ::googlex::protobuf::FileDescriptorProto* CodeGeneratorRequest::mutable_proto_file(int index) {
  // @@protoc_insertion_point(field_mutable:googlexprotobuf.compiler.CodeGeneratorRequest.proto_file)
  return proto_file_.Mutable(index);
}
inline ::googlex::protobuf::RepeatedPtrField< ::googlex::protobuf::FileDescriptorProto >*
CodeGeneratorRequest::mutable_proto_file() {
  // @@protoc_insertion_point(field_mutable_list:googlexprotobuf.compiler.CodeGeneratorRequest.proto_file)
  return &proto_file_;
}
inline const ::googlex::protobuf::FileDescriptorProto& CodeGeneratorRequest::proto_file(int index) const {
  // @@protoc_insertion_point(field_get:googlexprotobuf.compiler.CodeGeneratorRequest.proto_file)
  return proto_file_.Get(index);
}
inline ::googlex::protobuf::FileDescriptorProto* CodeGeneratorRequest::add_proto_file() {
  // @@protoc_insertion_point(field_add:googlexprotobuf.compiler.CodeGeneratorRequest.proto_file)
  return proto_file_.Add();
}
inline const ::googlex::protobuf::RepeatedPtrField< ::googlex::protobuf::FileDescriptorProto >&
CodeGeneratorRequest::proto_file() const {
  // @@protoc_insertion_point(field_list:googlexprotobuf.compiler.CodeGeneratorRequest.proto_file)
  return proto_file_;
}

// optional .googlexprotobuf.compiler.Version compiler_version = 3;
inline bool CodeGeneratorRequest::has_compiler_version() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void CodeGeneratorRequest::set_has_compiler_version() {
  _has_bits_[0] |= 0x00000002u;
}
inline void CodeGeneratorRequest::clear_has_compiler_version() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void CodeGeneratorRequest::clear_compiler_version() {
  if (compiler_version_ != NULL) compiler_version_->Clear();
  clear_has_compiler_version();
}
inline const ::googlex::protobuf::compiler::Version& CodeGeneratorRequest::_internal_compiler_version() const {
  return *compiler_version_;
}
inline const ::googlex::protobuf::compiler::Version& CodeGeneratorRequest::compiler_version() const {
  const ::googlex::protobuf::compiler::Version* p = compiler_version_;
  // @@protoc_insertion_point(field_get:googlexprotobuf.compiler.CodeGeneratorRequest.compiler_version)
  return p != NULL ? *p : *reinterpret_cast<const ::googlex::protobuf::compiler::Version*>(
      &::googlex::protobuf::compiler::_Version_default_instance_);
}
inline ::googlex::protobuf::compiler::Version* CodeGeneratorRequest::release_compiler_version() {
  // @@protoc_insertion_point(field_release:googlexprotobuf.compiler.CodeGeneratorRequest.compiler_version)
  clear_has_compiler_version();
  ::googlex::protobuf::compiler::Version* temp = compiler_version_;
  compiler_version_ = NULL;
  return temp;
}
inline ::googlex::protobuf::compiler::Version* CodeGeneratorRequest::mutable_compiler_version() {
  set_has_compiler_version();
  if (compiler_version_ == NULL) {
    auto* p = CreateMaybeMessage<::googlex::protobuf::compiler::Version>(GetArenaNoVirtual());
    compiler_version_ = p;
  }
  // @@protoc_insertion_point(field_mutable:googlexprotobuf.compiler.CodeGeneratorRequest.compiler_version)
  return compiler_version_;
}
inline void CodeGeneratorRequest::set_allocated_compiler_version(::googlex::protobuf::compiler::Version* compiler_version) {
  ::googlex::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete compiler_version_;
  }
  if (compiler_version) {
    ::googlex::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      compiler_version = ::googlex::protobuf::internal::GetOwnedMessage(
          message_arena, compiler_version, submessage_arena);
    }
    set_has_compiler_version();
  } else {
    clear_has_compiler_version();
  }
  compiler_version_ = compiler_version;
  // @@protoc_insertion_point(field_set_allocated:googlexprotobuf.compiler.CodeGeneratorRequest.compiler_version)
}

// -------------------------------------------------------------------

// CodeGeneratorResponse_File

// optional string name = 1;
inline bool CodeGeneratorResponse_File::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CodeGeneratorResponse_File::set_has_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CodeGeneratorResponse_File::clear_has_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CodeGeneratorResponse_File::clear_name() {
  name_.ClearToEmptyNoArena(&::googlex::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_name();
}
inline const ::std::string& CodeGeneratorResponse_File::name() const {
  // @@protoc_insertion_point(field_get:googlexprotobuf.compiler.CodeGeneratorResponse.File.name)
  return name_.GetNoArena();
}
inline void CodeGeneratorResponse_File::set_name(const ::std::string& value) {
  set_has_name();
  name_.SetNoArena(&::googlex::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:googlexprotobuf.compiler.CodeGeneratorResponse.File.name)
}
#if LANG_CXX11
inline void CodeGeneratorResponse_File::set_name(::std::string&& value) {
  set_has_name();
  name_.SetNoArena(
    &::googlex::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:googlexprotobuf.compiler.CodeGeneratorResponse.File.name)
}
#endif
inline void CodeGeneratorResponse_File::set_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_name();
  name_.SetNoArena(&::googlex::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:googlexprotobuf.compiler.CodeGeneratorResponse.File.name)
}
inline void CodeGeneratorResponse_File::set_name(const char* value, size_t size) {
  set_has_name();
  name_.SetNoArena(&::googlex::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:googlexprotobuf.compiler.CodeGeneratorResponse.File.name)
}
inline ::std::string* CodeGeneratorResponse_File::mutable_name() {
  set_has_name();
  // @@protoc_insertion_point(field_mutable:googlexprotobuf.compiler.CodeGeneratorResponse.File.name)
  return name_.MutableNoArena(&::googlex::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CodeGeneratorResponse_File::release_name() {
  // @@protoc_insertion_point(field_release:googlexprotobuf.compiler.CodeGeneratorResponse.File.name)
  if (!has_name()) {
    return NULL;
  }
  clear_has_name();
  return name_.ReleaseNonDefaultNoArena(&::googlex::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CodeGeneratorResponse_File::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    set_has_name();
  } else {
    clear_has_name();
  }
  name_.SetAllocatedNoArena(&::googlex::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:googlexprotobuf.compiler.CodeGeneratorResponse.File.name)
}

// optional string insertion_point = 2;
inline bool CodeGeneratorResponse_File::has_insertion_point() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void CodeGeneratorResponse_File::set_has_insertion_point() {
  _has_bits_[0] |= 0x00000002u;
}
inline void CodeGeneratorResponse_File::clear_has_insertion_point() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void CodeGeneratorResponse_File::clear_insertion_point() {
  insertion_point_.ClearToEmptyNoArena(&::googlex::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_insertion_point();
}
inline const ::std::string& CodeGeneratorResponse_File::insertion_point() const {
  // @@protoc_insertion_point(field_get:googlexprotobuf.compiler.CodeGeneratorResponse.File.insertion_point)
  return insertion_point_.GetNoArena();
}
inline void CodeGeneratorResponse_File::set_insertion_point(const ::std::string& value) {
  set_has_insertion_point();
  insertion_point_.SetNoArena(&::googlex::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:googlexprotobuf.compiler.CodeGeneratorResponse.File.insertion_point)
}
#if LANG_CXX11
inline void CodeGeneratorResponse_File::set_insertion_point(::std::string&& value) {
  set_has_insertion_point();
  insertion_point_.SetNoArena(
    &::googlex::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:googlexprotobuf.compiler.CodeGeneratorResponse.File.insertion_point)
}
#endif
inline void CodeGeneratorResponse_File::set_insertion_point(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_insertion_point();
  insertion_point_.SetNoArena(&::googlex::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:googlexprotobuf.compiler.CodeGeneratorResponse.File.insertion_point)
}
inline void CodeGeneratorResponse_File::set_insertion_point(const char* value, size_t size) {
  set_has_insertion_point();
  insertion_point_.SetNoArena(&::googlex::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:googlexprotobuf.compiler.CodeGeneratorResponse.File.insertion_point)
}
inline ::std::string* CodeGeneratorResponse_File::mutable_insertion_point() {
  set_has_insertion_point();
  // @@protoc_insertion_point(field_mutable:googlexprotobuf.compiler.CodeGeneratorResponse.File.insertion_point)
  return insertion_point_.MutableNoArena(&::googlex::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CodeGeneratorResponse_File::release_insertion_point() {
  // @@protoc_insertion_point(field_release:googlexprotobuf.compiler.CodeGeneratorResponse.File.insertion_point)
  if (!has_insertion_point()) {
    return NULL;
  }
  clear_has_insertion_point();
  return insertion_point_.ReleaseNonDefaultNoArena(&::googlex::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CodeGeneratorResponse_File::set_allocated_insertion_point(::std::string* insertion_point) {
  if (insertion_point != NULL) {
    set_has_insertion_point();
  } else {
    clear_has_insertion_point();
  }
  insertion_point_.SetAllocatedNoArena(&::googlex::protobuf::internal::GetEmptyStringAlreadyInited(), insertion_point);
  // @@protoc_insertion_point(field_set_allocated:googlexprotobuf.compiler.CodeGeneratorResponse.File.insertion_point)
}

// optional string content = 15;
inline bool CodeGeneratorResponse_File::has_content() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void CodeGeneratorResponse_File::set_has_content() {
  _has_bits_[0] |= 0x00000004u;
}
inline void CodeGeneratorResponse_File::clear_has_content() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void CodeGeneratorResponse_File::clear_content() {
  content_.ClearToEmptyNoArena(&::googlex::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_content();
}
inline const ::std::string& CodeGeneratorResponse_File::content() const {
  // @@protoc_insertion_point(field_get:googlexprotobuf.compiler.CodeGeneratorResponse.File.content)
  return content_.GetNoArena();
}
inline void CodeGeneratorResponse_File::set_content(const ::std::string& value) {
  set_has_content();
  content_.SetNoArena(&::googlex::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:googlexprotobuf.compiler.CodeGeneratorResponse.File.content)
}
#if LANG_CXX11
inline void CodeGeneratorResponse_File::set_content(::std::string&& value) {
  set_has_content();
  content_.SetNoArena(
    &::googlex::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:googlexprotobuf.compiler.CodeGeneratorResponse.File.content)
}
#endif
inline void CodeGeneratorResponse_File::set_content(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_content();
  content_.SetNoArena(&::googlex::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:googlexprotobuf.compiler.CodeGeneratorResponse.File.content)
}
inline void CodeGeneratorResponse_File::set_content(const char* value, size_t size) {
  set_has_content();
  content_.SetNoArena(&::googlex::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:googlexprotobuf.compiler.CodeGeneratorResponse.File.content)
}
inline ::std::string* CodeGeneratorResponse_File::mutable_content() {
  set_has_content();
  // @@protoc_insertion_point(field_mutable:googlexprotobuf.compiler.CodeGeneratorResponse.File.content)
  return content_.MutableNoArena(&::googlex::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CodeGeneratorResponse_File::release_content() {
  // @@protoc_insertion_point(field_release:googlexprotobuf.compiler.CodeGeneratorResponse.File.content)
  if (!has_content()) {
    return NULL;
  }
  clear_has_content();
  return content_.ReleaseNonDefaultNoArena(&::googlex::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CodeGeneratorResponse_File::set_allocated_content(::std::string* content) {
  if (content != NULL) {
    set_has_content();
  } else {
    clear_has_content();
  }
  content_.SetAllocatedNoArena(&::googlex::protobuf::internal::GetEmptyStringAlreadyInited(), content);
  // @@protoc_insertion_point(field_set_allocated:googlexprotobuf.compiler.CodeGeneratorResponse.File.content)
}

// -------------------------------------------------------------------

// CodeGeneratorResponse

// optional string error = 1;
inline bool CodeGeneratorResponse::has_error() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CodeGeneratorResponse::set_has_error() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CodeGeneratorResponse::clear_has_error() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CodeGeneratorResponse::clear_error() {
  error_.ClearToEmptyNoArena(&::googlex::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_error();
}
inline const ::std::string& CodeGeneratorResponse::error() const {
  // @@protoc_insertion_point(field_get:googlexprotobuf.compiler.CodeGeneratorResponse.error)
  return error_.GetNoArena();
}
inline void CodeGeneratorResponse::set_error(const ::std::string& value) {
  set_has_error();
  error_.SetNoArena(&::googlex::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:googlexprotobuf.compiler.CodeGeneratorResponse.error)
}
#if LANG_CXX11
inline void CodeGeneratorResponse::set_error(::std::string&& value) {
  set_has_error();
  error_.SetNoArena(
    &::googlex::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:googlexprotobuf.compiler.CodeGeneratorResponse.error)
}
#endif
inline void CodeGeneratorResponse::set_error(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_error();
  error_.SetNoArena(&::googlex::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:googlexprotobuf.compiler.CodeGeneratorResponse.error)
}
inline void CodeGeneratorResponse::set_error(const char* value, size_t size) {
  set_has_error();
  error_.SetNoArena(&::googlex::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:googlexprotobuf.compiler.CodeGeneratorResponse.error)
}
inline ::std::string* CodeGeneratorResponse::mutable_error() {
  set_has_error();
  // @@protoc_insertion_point(field_mutable:googlexprotobuf.compiler.CodeGeneratorResponse.error)
  return error_.MutableNoArena(&::googlex::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CodeGeneratorResponse::release_error() {
  // @@protoc_insertion_point(field_release:googlexprotobuf.compiler.CodeGeneratorResponse.error)
  if (!has_error()) {
    return NULL;
  }
  clear_has_error();
  return error_.ReleaseNonDefaultNoArena(&::googlex::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CodeGeneratorResponse::set_allocated_error(::std::string* error) {
  if (error != NULL) {
    set_has_error();
  } else {
    clear_has_error();
  }
  error_.SetAllocatedNoArena(&::googlex::protobuf::internal::GetEmptyStringAlreadyInited(), error);
  // @@protoc_insertion_point(field_set_allocated:googlexprotobuf.compiler.CodeGeneratorResponse.error)
}

// repeated .googlexprotobuf.compiler.CodeGeneratorResponse.File file = 15;
inline int CodeGeneratorResponse::file_size() const {
  return file_.size();
}
inline void CodeGeneratorResponse::clear_file() {
  file_.Clear();
}
inline ::googlex::protobuf::compiler::CodeGeneratorResponse_File* CodeGeneratorResponse::mutable_file(int index) {
  // @@protoc_insertion_point(field_mutable:googlexprotobuf.compiler.CodeGeneratorResponse.file)
  return file_.Mutable(index);
}
inline ::googlex::protobuf::RepeatedPtrField< ::googlex::protobuf::compiler::CodeGeneratorResponse_File >*
CodeGeneratorResponse::mutable_file() {
  // @@protoc_insertion_point(field_mutable_list:googlexprotobuf.compiler.CodeGeneratorResponse.file)
  return &file_;
}
inline const ::googlex::protobuf::compiler::CodeGeneratorResponse_File& CodeGeneratorResponse::file(int index) const {
  // @@protoc_insertion_point(field_get:googlexprotobuf.compiler.CodeGeneratorResponse.file)
  return file_.Get(index);
}
inline ::googlex::protobuf::compiler::CodeGeneratorResponse_File* CodeGeneratorResponse::add_file() {
  // @@protoc_insertion_point(field_add:googlexprotobuf.compiler.CodeGeneratorResponse.file)
  return file_.Add();
}
inline const ::googlex::protobuf::RepeatedPtrField< ::googlex::protobuf::compiler::CodeGeneratorResponse_File >&
CodeGeneratorResponse::file() const {
  // @@protoc_insertion_point(field_list:googlexprotobuf.compiler.CodeGeneratorResponse.file)
  return file_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace compiler
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_googlex2fprotobuf_2fcompiler_2fplugin_2eproto
