// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/protobuf/duration.proto

#ifndef PROTOBUF_INCLUDED_googlex2fprotobuf_2fduration_2eproto
#define PROTOBUF_INCLUDED_googlex2fprotobuf_2fduration_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_googlex2fprotobuf_2fduration_2eproto LIBPROTOBUF_EXPORT

namespace protobuf_googlex2fprotobuf_2fduration_2eproto {
// Internal implementation detail -- do not use these members.
struct LIBPROTOBUF_EXPORT TableStruct {
  static const ::googlex::protobuf::internal::ParseTableField entries[];
  static const ::googlex::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::googlex::protobuf::internal::ParseTable schema[1];
  static const ::googlex::protobuf::internal::FieldMetadata field_metadata[];
  static const ::googlex::protobuf::internal::SerializationTable serialization_table[];
  static const ::googlex::protobuf::uint32 offsets[];
};
void LIBPROTOBUF_EXPORT AddDescriptors();
}  // namespace protobuf_googlex2fprotobuf_2fduration_2eproto
namespace googlex{
namespace protobuf {
class Duration;
class DurationDefaultTypeInternal;
LIBPROTOBUF_EXPORT extern DurationDefaultTypeInternal _Duration_default_instance_;
}  // namespace protobuf
}  // namespace google
namespace googlex{
namespace protobuf {
template<> LIBPROTOBUF_EXPORT ::googlex::protobuf::Duration* Arena::CreateMaybeMessage<::googlex::protobuf::Duration>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace googlex{
namespace protobuf {

// ===================================================================

class LIBPROTOBUF_EXPORT Duration : public ::googlex::protobuf::Message /* @@protoc_insertion_point(class_definition:googlexprotobuf.Duration) */ {
 public:
  Duration();
  virtual ~Duration();

  Duration(const Duration& from);

  inline Duration& operator=(const Duration& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Duration(Duration&& from) noexcept
    : Duration() {
    *this = ::std::move(from);
  }

  inline Duration& operator=(Duration&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline ::googlex::protobuf::Arena* GetArena() const final {
    return GetArenaNoVirtual();
  }
  inline void* GetMaybeArenaPointer() const final {
    return MaybeArenaPtr();
  }
  static const ::googlex::protobuf::Descriptor* descriptor();
  static const Duration& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Duration* internal_default_instance() {
    return reinterpret_cast<const Duration*>(
               &_Duration_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void UnsafeArenaSwap(Duration* other);
  void Swap(Duration* other);
  friend void swap(Duration& a, Duration& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Duration* New() const final {
    return CreateMaybeMessage<Duration>(NULL);
  }

  Duration* New(::googlex::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Duration>(arena);
  }
  void CopyFrom(const ::googlex::protobuf::Message& from) final;
  void MergeFrom(const ::googlex::protobuf::Message& from) final;
  void CopyFrom(const Duration& from);
  void MergeFrom(const Duration& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::googlex::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::googlex::protobuf::io::CodedOutputStream* output) const final;
  ::googlex::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::googlex::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Duration* other);
  protected:
  explicit Duration(::googlex::protobuf::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::googlex::protobuf::Arena* arena);
  private:
  inline ::googlex::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::googlex::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int64 seconds = 1;
  void clear_seconds();
  static const int kSecondsFieldNumber = 1;
  ::googlex::protobuf::int64 seconds() const;
  void set_seconds(::googlex::protobuf::int64 value);

  // int32 nanos = 2;
  void clear_nanos();
  static const int kNanosFieldNumber = 2;
  ::googlex::protobuf::int32 nanos() const;
  void set_nanos(::googlex::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:googlexprotobuf.Duration)
 private:

  ::googlex::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  template <typename T> friend class ::googlex::protobuf::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::googlex::protobuf::int64 seconds_;
  ::googlex::protobuf::int32 nanos_;
  mutable ::googlex::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_googlex2fprotobuf_2fduration_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Duration

// int64 seconds = 1;
inline void Duration::clear_seconds() {
  seconds_ = GOOGLE_LONGLONG(0);
}
inline ::googlex::protobuf::int64 Duration::seconds() const {
  // @@protoc_insertion_point(field_get:googlexprotobuf.Duration.seconds)
  return seconds_;
}
inline void Duration::set_seconds(::googlex::protobuf::int64 value) {
  
  seconds_ = value;
  // @@protoc_insertion_point(field_set:googlexprotobuf.Duration.seconds)
}

// int32 nanos = 2;
inline void Duration::clear_nanos() {
  nanos_ = 0;
}
inline ::googlex::protobuf::int32 Duration::nanos() const {
  // @@protoc_insertion_point(field_get:googlexprotobuf.Duration.nanos)
  return nanos_;
}
inline void Duration::set_nanos(::googlex::protobuf::int32 value) {
  
  nanos_ = value;
  // @@protoc_insertion_point(field_set:googlexprotobuf.Duration.nanos)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_googlex2fprotobuf_2fduration_2eproto
